export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOAD_TRANSICTION = "LOAD_TRANSICTION";
export const LOAD_TRANSICTION_USER = "LOAD_TRANSICTION_USER";